language: python
env:
  global:
    - SECRET_KEY=travis
    - DJANGO_SETTINGS_MODULE="website.settings.travis"
    - DATABASE_ENGINE="django.db.backends.postgresql_psycopg2"
    - DATABASE_NAME=zika
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=""
    - DATABASE_HOST=127.0.0.1
    - DATABASE_PORT=5432
    - DOCKER_COMPOSE_VERSION=1.7.0
matrix:
  include:
    - os: linux
      python: "3.5"
      env: PYTHON=/usr/bin/python3.5
      services: postgresql

script:
  - python manage.py test
notifications:
  email:
    recipients:
      - ecaldwe1@nd.edu
      - avyushko@nd.edu
    on_success: always
    on_failure: always